language: python
sudo: required
os: linux
dist: bionic
compiler: gcc

python: 
  - "3.7"
  
install:
  - pip3 install Cython
  - pip3 install setuptools
  - pip3 install wheel
  - pip3 install pandas 
  - pip3 install numpy
  - pip3 install statsmodels
  - pip3 install sphinx
  - pip3 install numba
  - installationpath=$PWD
  - echo $installationpath
  - python3 setup.py install
  - cd tests
  - installationpath=$PWD
  - echo $installationpath

script:
  - grafimo -h
  - grafimo --version
  - grafimo --help
